#!/usr/bin/env node

var argv = require('optimist').argv;
var verbose = true === argv.v;
var clc = require('cli-color');


var exec = require('child_process').exec;
var child;

child = exec('nodeunit tests/unit/*', function(error, stdout, stderr) {
    console.log(">>>>> Running unit tests");

    if (error) {
        console.log(stdout);
        console.log(clc.bgRed('Unit tests failed'));
        process.exit(1); // abort
    } else {
        if (verbose) {
            console.log(stdout);
        }
        console.log(clc.bgGreen('Unit tests passed successfully'));
    }
});


// -----------------------------------------------------------------------------


var exec = require('child_process').exec;
var child;

child = exec('node tests/functional/index.js', function(error, stdout, stderr) {
    console.log("\n >>>>> Running functional tests");

    if (error) {
        console.log(stdout);
        console.log(clc.bgRed('Functional tests failed'));
        process.exit(1); // abort
    } else {
        if (verbose) {
            console.log(stdout);
        }
        console.log(clc.bgGreen('Functional tests passed successfully'));
    }
});
