#!/usr/bin/env node

var clc = require('cli-color');

console.log('>>>>> Running unit tests on Git pre-commit');

var exec = require('child_process').exec;
var child;

child = exec('nodeunit tests/unit/*', function(error, stdout, stderr) {
    if (error) {
        console.log(clc.bgRed('Unit tests failed'));
        console.log(stdout);
        process.exit(1); // abort 
    } else {
        console.log(clc.bgGreen('Unit tests passed successfully'));
        process.exit();
    }
});